# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - script: |
      go version
      go get -v -t -d ./...
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies'

  - script: |
      pwd
      ls -al
      ls -al ../
      ls -al ../../
      ls -al ../../../
      ls -al ../../../../
      bash build.sh
    workingDirectory: '$(modulePath)'
    continueOnError: 'false'
    displayName: 'Build app'

  - script: |
      wget -P data/indiv18/ https://f001.backblazeb2.com/file/352fa7aef7f4649aac8353d380067bb692871345/itcont_1e6.txt.gz
      gunzip data/indiv18/itcont_1e6.txt.gz
    workingDirectory: '$(modulePath)'
    continueOnError: 'false'
    displayName: 'Prepare benchmarks'

  - script: |
      ./bin/rev0 data/indiv18/itcont_1e6.txt
      ./bin/rev0 data/indiv18/itcont_1e6.txt
      ./bin/rev0 data/indiv18/itcont_1e6.txt
      ./bin/rev10 data/indiv18/itcont_1e6.txt
      ./bin/rev10 data/indiv18/itcont_1e6.txt
      ./bin/rev10 data/indiv18/itcont_1e6.txt
    workingDirectory: '$(modulePath)'
    continueOnError: 'false'
    displayName: 'Run benchmarks'